defmodule AshExpo.Codegen do
  @moduledoc """
  Deterministically renders the Expo support files consumed next to
  `ash_typescript` generated clients.
  """

  alias AshExpo.Manifest

  @manifest_file "ash_expo_manifest.ts"
  @runtime_file "ash_expo_runtime.ts"
  @index_file "ash_expo.ts"

  @doc "Returns generated path/content pairs without touching the filesystem."
  def generate(resources, output_dir \\ "assets/js") do
    manifest = Manifest.build(resources)

    %{
      Path.join(output_dir, @manifest_file) => render_manifest(manifest),
      Path.join(output_dir, @runtime_file) => render_runtime(),
      Path.join(output_dir, @index_file) => render_index()
    }
  end

  @doc "Writes changed generated files and returns the paths that changed."
  def write!(resources, output_dir \\ "assets/js") do
    resources
    |> generate(output_dir)
    |> Enum.reduce([], fn {path, content}, changed ->
      current = if File.exists?(path), do: File.read!(path), else: nil

      if current == content do
        changed
      else
        File.mkdir_p!(Path.dirname(path))
        File.write!(path, content)
        [path | changed]
      end
    end)
    |> Enum.reverse()
  end

  @doc "Raises when committed generated files are stale."
  def check!(resources, output_dir \\ "assets/js") do
    stale =
      resources
      |> generate(output_dir)
      |> Enum.flat_map(fn {path, content} ->
        if File.exists?(path) and File.read!(path) == content, do: [], else: [path]
      end)

    if stale != [] do
      raise "AshExpo generated files are stale: #{Enum.join(stale, ", ")}"
    end

    :ok
  end

  @doc false
  def render_manifest(manifest) do
    json = Jason.encode!(manifest, pretty: true)

    """
    // Generated by ash_expo. Do not edit by hand.
    export const ashExpoManifest = #{json} as const;

    export type AshExpoManifest = typeof ashExpoManifest;
    export type AshExpoResource = AshExpoManifest["resources"][number];
    export type AshExpoAction = AshExpoResource["actions"][number];
    """
  end

  @doc false
  def render_index do
    """
    // Generated by ash_expo. Do not edit by hand.
    export * from "./ash_expo_manifest";
    export * from "./ash_expo_runtime";
    """
  end

  @doc false
  def render_runtime do
    """
    // Generated by ash_expo. Do not edit by hand.
    // Compatible with ash_typescript's per-call `customFetch` option.

    import { ashExpoManifest } from "./ash_expo_manifest";

    export type AshExpoFetch = (
      input: RequestInfo | URL,
      init?: RequestInit,
    ) => Promise<Response>;

    export interface AshExpoTokenStore {
      getToken(): Promise<string | null>;
      setToken(token: string): Promise<void>;
      clearToken(): Promise<void>;
    }

    export interface AshExpoClientOptions {
      fetch: AshExpoFetch;
      tokenStore?: AshExpoTokenStore;
      getNetworkOnline?: () => boolean | Promise<boolean>;
      authorizationHeader?: string;
      authorizationScheme?: string;
    }

    export type AshExpoActionConfig = Record<string, unknown> & {
      headers?: Record<string, string>;
      customFetch?: AshExpoFetch;
      hookCtx?: Record<string, unknown>;
    };

    export type AshExpoOfflineClass =
      | "online_only"
      | "cacheable"
      | "idempotent"
      | "replayable";

    export class AshExpoAdmissionError extends Error {
      constructor(message: string) {
        super(message);
        this.name = "AshExpoAdmissionError";
      }
    }

    export function findAshExpoAction(resource: string, action: string) {
      const resourceEntry = ashExpoManifest.resources.find(
        (candidate) => candidate.module === resource || candidate.typeName === resource,
      );

      return resourceEntry?.actions.find((candidate) => candidate.name === action);
    }

    export function createAshExpoClient(options: AshExpoClientOptions) {
      const authHeader = options.authorizationHeader ?? "authorization";
      const authScheme = options.authorizationScheme ?? "Bearer";

      const mobileFetch: AshExpoFetch = async (input, init = {}) => {
        const headers = new Headers(init.headers ?? {});
        const token = await options.tokenStore?.getToken();

        if (token && !headers.has(authHeader)) {
          headers.set(authHeader, `${authScheme} ${token}`);
        }

        return options.fetch(input, { ...init, headers });
      };

      async function assertAdmitted(
        resource: string,
        action: string,
        mode: "execute" | "queue" = "execute",
      ) {
        const projection = findAshExpoAction(resource, action);

        if (!projection) {
          throw new AshExpoAdmissionError(
            `No AshExpo projection exists for ${resource}.${action}`,
          );
        }

        if (mode === "queue" && projection.offline === "online_only") {
          throw new AshExpoAdmissionError(
            `${resource}.${action} is online_only and cannot be queued`,
          );
        }

        if (mode === "execute" && options.getNetworkOnline) {
          const online = await options.getNetworkOnline();
          if (!online && projection.offline === "online_only") {
            throw new AshExpoAdmissionError(
              `${resource}.${action} requires an online server admission`,
            );
          }
        }

        return projection;
      }

      function action<T extends AshExpoActionConfig>(config: T): T & {
        customFetch: AshExpoFetch;
      } {
        return {
          ...config,
          customFetch: mobileFetch,
        };
      }

      return {
        action,
        assertAdmitted,
        fetch: mobileFetch,
        manifest: ashExpoManifest,
        tokenStore: options.tokenStore,
      } as const;
    }

    export function createSecureStoreTokenStore(
      secureStore: {
        getItemAsync(key: string): Promise<string | null>;
        setItemAsync(key: string, value: string): Promise<void>;
        deleteItemAsync(key: string): Promise<void>;
      },
      key = "ash_expo.auth_token",
    ): AshExpoTokenStore {
      return {
        getToken: () => secureStore.getItemAsync(key),
        setToken: (token) => secureStore.setItemAsync(key, token),
        clearToken: () => secureStore.deleteItemAsync(key),
      };
    }
    """
  end
end
