defmodule AshExpo.Codegen do
  @moduledoc """
  Deterministically renders the Expo support files consumed next to
  `ash_typescript` generated clients.
  """

  alias AshExpo.Manifest

  @manifest_file "ash_expo_manifest.ts"
  @runtime_file "ash_expo_runtime.ts"
  @index_file "ash_expo.ts"

  @doc "Returns generated path/content pairs without touching the filesystem."
  def generate(resources, output_dir \\ "assets/js") do
    manifest = Manifest.build(resources)

    %{
      Path.join(output_dir, @manifest_file) => render_manifest(manifest),
      Path.join(output_dir, @runtime_file) => render_runtime(),
      Path.join(output_dir, @index_file) => render_index()
    }
  end

  @doc "Writes changed generated files and returns the paths that changed."
  def write!(resources, output_dir \\ "assets/js") do
    resources
    |> generate(output_dir)
    |> Enum.reduce([], fn {path, content}, changed ->
      current = if File.exists?(path), do: File.read!(path), else: nil

      if current == content do
        changed
      else
        File.mkdir_p!(Path.dirname(path))
        File.write!(path, content)
        [path | changed]
      end
    end)
    |> Enum.reverse()
  end

  @doc "Raises when committed generated files are stale."
  def check!(resources, output_dir \\ "assets/js") do
    stale =
      resources
      |> generate(output_dir)
      |> Enum.flat_map(fn {path, content} ->
        if File.exists?(path) and File.read!(path) == content, do: [], else: [path]
      end)

    if stale != [] do
      raise "AshExpo generated files are stale: #{Enum.join(stale, ", ")}"
    end

    :ok
  end

  @doc false
  def render_manifest(manifest) do
    json = Jason.encode!(manifest, pretty: true)

    """
    // Generated by ash_expo. Do not edit by hand.
    export interface AshExpoManifestAction {
      readonly name: string;
      readonly type: string;
      readonly transport: "http" | "channel";
      readonly offline: "online_only" | "cacheable" | "idempotent" | "replayable";
      readonly realtime: boolean;
      readonly secure: boolean;
    }

    export interface AshExpoManifestResource {
      readonly module: string;
      readonly typeName: string;
      readonly actions: readonly AshExpoManifestAction[];
    }

    export interface AshExpoManifestShape {
      readonly schemaVersion: number;
      readonly resources: readonly AshExpoManifestResource[];
    }

    export const ashExpoManifest = #{json} as const satisfies AshExpoManifestShape;

    export type AshExpoManifest = typeof ashExpoManifest;
    export type AshExpoResource = AshExpoManifestResource;
    export type AshExpoAction = AshExpoManifestAction;
    """
  end

  @doc false
  def render_index do
    """
    // Generated by ash_expo. Do not edit by hand.
    export * from "./ash_expo_manifest";
    export * from "./ash_expo_runtime";
    """
  end

  @doc false
  def render_runtime do
    """
    // Generated by ash_expo. Do not edit by hand.
    // Compatible with ash_typescript HTTP and Phoenix Channel RPC projections.

    import {
      ashExpoManifest,
      type AshExpoManifestResource,
    } from "./ash_expo_manifest";

    export type AshExpoFetch = (
      input: RequestInfo | URL,
      init?: RequestInit,
    ) => Promise<Response>;

    export interface AshExpoTokenStore {
      getToken(): Promise<string | null>;
      setToken(token: string): Promise<void>;
      clearToken(): Promise<void>;
    }

    export interface AshExpoClientOptions<TChannel = never> {
      fetch: AshExpoFetch;
      baseUrl?: string;
      channel?: TChannel;
      tokenStore?: AshExpoTokenStore;
      getNetworkOnline?: () => boolean | Promise<boolean>;
      authorizationHeader?: string;
      authorizationScheme?: string;
    }

    export type AshExpoActionConfig = Record<string, unknown> & {
      headers?: Record<string, string>;
      customFetch?: AshExpoFetch;
      hookCtx?: Record<string, unknown>;
    };

    export type AshExpoOfflineClass =
      | "online_only"
      | "cacheable"
      | "idempotent"
      | "replayable";

    export type AshExpoAdmissionMode = "execute" | "queue";
    export type AshExpoTransport = "http" | "channel";

    export class AshExpoAdmissionError extends Error {
      constructor(message: string) {
        super(message);
        this.name = "AshExpoAdmissionError";
      }
    }

    export class AshExpoConfigurationError extends Error {
      constructor(message: string) {
        super(message);
        this.name = "AshExpoConfigurationError";
      }
    }

    export function createAshExpoSocketUrl(baseUrl: string, path = "/socket"): string {
      const url = new URL(path, baseUrl);

      if (url.protocol === "https:") {
        url.protocol = "wss:";
      } else if (url.protocol === "http:") {
        url.protocol = "ws:";
      } else if (url.protocol !== "ws:" && url.protocol !== "wss:") {
        throw new AshExpoConfigurationError(
          `Unsupported socket base protocol: ${url.protocol}`,
        );
      }

      return url.toString();
    }

    export async function createAshExpoSocketParams(
      tokenStore?: AshExpoTokenStore,
      extra: Record<string, unknown> = {},
      tokenParam = "authToken",
    ): Promise<Record<string, unknown>> {
      const token = await tokenStore?.getToken();
      return token ? { ...extra, [tokenParam]: token } : extra;
    }

    export function findAshExpoAction(resource: string, action: string) {
      const resources: readonly AshExpoManifestResource[] = ashExpoManifest.resources;
      const resourceEntry = resources.find(
        (candidate) => candidate.module === resource || candidate.typeName === resource,
      );

      return resourceEntry?.actions.find((candidate) => candidate.name === action);
    }

    export function createAshExpoClient<TChannel = never>(
      options: AshExpoClientOptions<TChannel>,
    ) {
      const authHeader = options.authorizationHeader ?? "authorization";
      const authScheme = options.authorizationScheme ?? "Bearer";

      function requireProjection(resource: string, actionName: string) {
        const projection = findAshExpoAction(resource, actionName);

        if (!projection) {
          throw new AshExpoAdmissionError(
            `No AshExpo projection exists for ${resource}.${actionName}`,
          );
        }

        return projection;
      }

      function requireTransport(
        resource: string,
        actionName: string,
        expected: AshExpoTransport,
      ) {
        const projection = requireProjection(resource, actionName);

        if (projection.transport !== expected) {
          throw new AshExpoAdmissionError(
            `${resource}.${actionName} requires ${projection.transport} transport, not ${expected}`,
          );
        }

        return projection;
      }

      function resolveInput(input: RequestInfo | URL): RequestInfo | URL {
        if (!options.baseUrl || typeof input !== "string") {
          return input;
        }

        try {
          return new URL(input);
        } catch {
          return new URL(input, options.baseUrl);
        }
      }

      const publicFetch: AshExpoFetch = async (input, init = {}) =>
        options.fetch(resolveInput(input), init);

      const authenticatedFetch: AshExpoFetch = async (input, init = {}) => {
        const headers = new Headers(init.headers ?? {});
        const token = await options.tokenStore?.getToken();

        if (token && !headers.has(authHeader)) {
          headers.set(authHeader, `${authScheme} ${token}`);
        }

        return options.fetch(resolveInput(input), { ...init, headers });
      };

      async function assertAdmitted(
        resource: string,
        actionName: string,
        mode: AshExpoAdmissionMode = "execute",
      ) {
        const projection = requireProjection(resource, actionName);

        if (mode === "queue" && projection.transport === "channel") {
          throw new AshExpoAdmissionError(
            `${resource}.${actionName} uses channel transport and cannot be queued`,
          );
        }

        if (mode === "queue" && projection.offline === "online_only") {
          throw new AshExpoAdmissionError(
            `${resource}.${actionName} is online_only and cannot be queued`,
          );
        }

        if (mode === "execute" && options.getNetworkOnline) {
          const online = await options.getNetworkOnline();
          if (!online && projection.offline === "online_only") {
            throw new AshExpoAdmissionError(
              `${resource}.${actionName} requires an online server admission`,
            );
          }
        }

        return projection;
      }

      function action<T extends AshExpoActionConfig>(
        resource: string,
        actionName: string,
        config: T,
      ): T & { customFetch: AshExpoFetch } {
        const projection = requireTransport(resource, actionName, "http");

        return {
          ...config,
          customFetch: projection.secure ? authenticatedFetch : publicFetch,
        };
      }

      function channelAction<T extends Record<string, unknown>>(
        resource: string,
        actionName: string,
        config: T,
      ): T & { channel: TChannel } {
        requireTransport(resource, actionName, "channel");
        const channel = options.channel;

        if (channel === undefined) {
          throw new AshExpoConfigurationError(
            `No Phoenix Channel configured for ${resource}.${actionName}`,
          );
        }

        return { ...config, channel: channel as TChannel };
      }

      async function prepare<T extends AshExpoActionConfig>(
        resource: string,
        actionName: string,
        config: T,
        mode: AshExpoAdmissionMode = "execute",
      ): Promise<T & { customFetch: AshExpoFetch }> {
        await assertAdmitted(resource, actionName, mode);
        return action(resource, actionName, config);
      }

      async function prepareChannel<T extends Record<string, unknown>>(
        resource: string,
        actionName: string,
        config: T,
      ): Promise<T & { channel: TChannel }> {
        await assertAdmitted(resource, actionName, "execute");
        return channelAction(resource, actionName, config);
      }

      return {
        action,
        assertAdmitted,
        channelAction,
        fetch: authenticatedFetch,
        manifest: ashExpoManifest,
        prepare,
        prepareChannel,
        publicFetch,
        tokenStore: options.tokenStore,
      } as const;
    }

    export function createSecureStoreTokenStore(
      secureStore: {
        getItemAsync(key: string): Promise<string | null>;
        setItemAsync(key: string, value: string): Promise<void>;
        deleteItemAsync(key: string): Promise<void>;
      },
      key = "ash_expo.auth_token",
    ): AshExpoTokenStore {
      return {
        getToken: () => secureStore.getItemAsync(key),
        setToken: (token) => secureStore.setItemAsync(key, token),
        clearToken: () => secureStore.deleteItemAsync(key),
      };
    }
    """
  end
end
